spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/walletdb
    username: wallet
    password: wallet
  flyway:
    enabled: false
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,metrics